### PR TITLE
Add a binary for waiting for a port

### PR DESCRIPTION
**Pull request by mmalecki**
Exit with 0 as soon as the port is available.

### CODE REVIEW

**Comment by Chris927** [comment]
Thanks, @mmalecki!

"wait-for-port" is probably a better name than "wait-for-host"...

**Comment by mmalecki** [comment]
@Chris927 :+1: 

Would you mind releasing this one to npm?

**Comment by Chris927** [comment]
Sure! Released as v0.0.2.

**Comment by mmalecki** [comment]
@Chris927 Thanks!

**Pull request merged**
